imports:
  - /var/www/vendor/oro/platform/src/Oro/Bundle/TestFrameworkBundle/Resources/config/behat.yml.dist

default: &default
    gherkin:
        filters:
            tags: ~@not-automated&&~@skip
    extensions:
        Behat\MinkExtension:
            base_url: 'http://minion/'
            default_session: 'first_session'
            sessions:
                first_session:
                    oroSelenium2:
                        wd_host: "http://phantomjs:8910/wd/hub"
        Behat\Symfony2Extension: ~
        Oro\Bundle\TestFrameworkBundle\Behat\ServiceContainer\OroTestFrameworkExtension:
            reference_initializer_class: Oro\Bundle\ApplicationBundle\Tests\Behat\ReferenceRepositoryInitializer
            shared_contexts:
                - Oro\Bundle\ApplicationBundle\Tests\Behat\Context\CommerceMainContext
                - Oro\Bundle\SalesBundle\Tests\Behat\Context\SalesContext
                - Oro\Bundle\ShippingBundle\Tests\Behat\Context\SingleCurrencyContext
            application_suites:
                - OroApplicationBundle
                - OroUserBundle
                - OroCRMBundle
                - OroNavigationBundle
                - OroContactBundle
                - OroAccountBundle
                - OroTaskBundle
                - OroEmailBundle
                - OroHelpBundle
                - OroSearchBundle
                - OroDashboardBundle
                - OroApplicationBundle
#                @todo Uncomment after resolve BB-4971
#                - OroShippingBundle

selenium2:
    <<: *default
#    Uncomment this in your behat.yml for run tests with Chrome browser
#    extensions:
#        Behat\MinkExtension:
#            browser_name: chrome
#            base_url: 'http://dev-commerce-crm.local/'
